web:
  build: .
  environment:
    - PORT=8080
    - MONGO_DB_CONNECTION=mongodb://mongodb:27017/gocrud
    - MONGO_DB_NAME=gocrud
  volumes:
    - .:/go/src/github.com/brettscott/gocrud
  ports:
    - "8080:8080"
  links:
    - mongodb

mongodb:
  image: mongo
  ports:
    - "27017:27017"

#acceptance_test:
#  build: acceptance-tests
#  environment:
#    - BASE_URL=http://web:8080
#  links:
#   - web
#  volumes:
#   - ./acceptance-tests:/go/src/github.com/brettscott/gocrud/acceptance-tests
#
